### ISSUE TITLE
Start using nestjs, instead of normal fastify

### ISSUE THREAD

**Issue by kymppi** [rittaschool/ritta-server#52]
For me atleast, i think it would be easier to maintain with use of nestjs. It would allow you to use decorators and depedency injection. Of course you could do this without nestjs, but with nest its easier.

**Comment by kymppi** [comment]
Nestjs also supports both express.js and fastify.

**Comment by niilasoika** [comment]
[kymppi/ritta-server](https://github.com/kymppi/ritta-server) :)

**Comment by kymppi** [comment]
Remember to use the "nest" branch :-)
